// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    HeaderBackdrop: typeof import('./components/layout/HeaderBackdrop.vue')['default']
    HeaderFadingBackdrop: typeof import('./components/layout/HeaderFadingBackdrop.vue')['default']
    Logo: typeof import('./components/brand/Logo.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/layout/SideMenu.vue')['default']
  }
}
